name: Core
version: 7.0
author: MasterDash5
softdepend: [LuckPerms]
main: dashnetwork.core.bukkit.Core

commands:
  anvil:
  center:
  clearlag:
    aliases: [cl]
  console:
  mommy:
    aliases: [daddy, grandma, grandpa, aunt, uncle]
  nightvision:
    aliases: [nv, see]
  oplist:
    aliases: [ops]
  respawn:
    aliases: [forcerespawn]
  serverinfo:
  spin:
    aliases: [spinmerightround, spinmerightroundbabyrightround]